import inspect
import typing

import requests
import rich

from resideo import config, device, user

BASE_URL = "https://api.honeywellhome.com/v2"


class Location:
    """
    Contains data about a location.
    """

    baseUrl: str = BASE_URL
    oauthToken: str
    refreshToken: str
    apiKey: str

    locationID: int
    name: str
    country: str
    zipcode: int
    devices: list[device.Thermostat] = []
    users: list[user.User] = []
    timeZoneId: str
    timeZone: str
    ianaTimeZone: str
    daylightSavingTimeEnabled: bool
    geoFenceEnabled: bool
    predictiveAIREnabled: bool
    predictiveAIREnabled: bool
    comfortLevel: int
    geoFenceNotificationEnabled: bool
    geoFenceNotificationTypeId: int
    configuration: config.Config

    def __init__(self, oauthToken: str, refreshToken: str, apiKey: str):
        """Initializes a location.

        Args:
            oauthToken: Token generated by OAuth. https://developer.honeywellhome.com/content/oauth2-guide
            refreshToken: Token for refreshing access token
            apiKey: API token from Resideo App.
        """
        self.oauthToken = oauthToken
        self.refreshToken = refreshToken
        self.apiKey = apiKey
        self.accessToken = getAccessToken(oauthToken, refreshToken)

        for key, value in self._getLocation().items():
            if inspect.get_annotations(type(self)).get(key) == list[device.Thermostat]:
                for deviceData in value:
                    self.devices.append(
                        device.Thermostat(
                            oauthToken=self.oauthToken,
                            refreshToken=self.refreshToken,
                            apiKey=self.apiKey,
                            locationId=self.locationID,
                            accessToken=self.accessToken,
                            **deviceData,
                        )
                    )
            elif inspect.get_annotations(type(self)).get(key) == list[user.User]:
                for userData in value:
                    self.users.append(user.User(**userData))
            elif inspect.get_annotations(type(self)).get(key) == config.Config:
                self.configuration = config.Config(**value)
            else:
                self.__dict__[key] = typing.cast(
                    inspect.get_annotations(type(self)).get(key), value
                )

    def _getLocation(self):
        """
        Makes API call to get data about a location. Limited to account that only have single location.

        Returns:
            API JSON response data
        """
        endpoint = "/locations"
        response = requests.get(
            self.baseUrl + endpoint,
            headers={"Authorization": f"Bearer {self.accessToken}"},
            params={"apikey": self.apiKey},
        )
        return response.json()[0]


def getAccessToken(oauthToken: str, refreshToken: str) -> str:
    """Gets authentication token"""
    url = "https://api.honeywellhome.com/oauth2/token"

    refreshToken = "zs70SGumUnqZUOwyZPMrS05yVFsgXGBg"
    response = requests.post(
        url,
        data={
            "grant_type": "refresh_token",
            "refresh_token": refreshToken,
        },
        headers={
            "Authorization": oauthToken,
            "Content-Type": "application/x-www-form-urlencoded",
        },
    )

    return response.json()["access_token"]


if __name__ == "__main__":
    refreshToken = "zs70SGumUnqZUOwyZPMrS05yVFsgXGBg"
    oauthToken = "RUFFa1M2QW9nbmZlS3JaYzNpR3V2RXB1NG96QjdGQ0E6UFk4bUtPZnJhVUc5Tk4wMg=="
    apiKey = "EAEkS6AognfeKrZc3iGuvEpu4ozB7FCA"

    home = Location(oauthToken=oauthToken, refreshToken=refreshToken, apiKey=apiKey)
    home.devices[0].setTemp(temp=68, mode="Heat")
